version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    template = '{{.Icon}} '
    foreground = 'p:os'

  # [[blocks.segments]]
  #   type = 'session'
  #   style = 'plain'
  #   template = '{{ .UserName }}@{{ .HostName }} '
  #   foreground = 'p:blue'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .Path }} '
    foreground = 'p:blue'

    [blocks.segments.properties]
      style = 'full'
      # folder_icon = '....'
      # home_icon = '~'
      # style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = '{{ .HEAD }} '
    foreground = 'p:pink'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:lavender'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ else }}{{ .Full }}{{ end }}{{ end }} '

    [blocks.segments.properties]
      fetch_virtual_env = true
      display_mode = 'always'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:blue'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ''
    foreground = 'p:closer'

[transient_prompt]
  template = ' '
  foreground = 'p:closer'

[secondary_prompt]
  template = ' '
  foreground = 'p:closer'

[palette]
  blue = '#89B4FA'
  closer = 'p:os'
  lavender = '#B4BEFE'
  os = '#ACB0BE'
  pink = '#F5C2E7'
